# These are supported funding model platforms

github: a-bonfim-tech
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: a.bonfim.tech  api_fa8e40c8bdb3b6de7804bf90f9c21c4d623bfd9351f34f93317ac63675df3da5
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: buymeacoffee.com/a.bonfim.tech
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']


<script src="https://liberapay.com/a.bonfim.tech/widgets/button.js"></script>
<noscript><a href="https://liberapay.com/a.bonfim.tech/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a></noscript>
